CREATE TABLE IF NOT EXISTS trips (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    vendor_id             TINYINT,
    pickup_datetime       DATETIME,
    dropoff_datetime      DATETIME,
    passenger_count       TINYINT,
    trip_distance         FLOAT,
    pickup_location_id    SMALLINT,
    dropoff_location_id   SMALLINT,
    payment_type          TINYINT,
    fare_amount           DECIMAL(8,2),
    extra                 DECIMAL(6,2),
    mta_tax               DECIMAL(6,2),
    tip_amount            DECIMAL(8,2),
    tolls_amount          DECIMAL(8,2),
    congestion_surcharge  DECIMAL(6,2),
    airport_fee           DECIMAL(6,2),
    total_amount          DECIMAL(8,2),
    trip_duration_minutes FLOAT,
    revenue_per_minute    DECIMAL(8,4),
    INDEX idx_pickup  (pickup_datetime),
    INDEX idx_pu_zone (pickup_location_id),
    INDEX idx_payment (payment_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
